const express = require("express");
const roomRouter = require("./roomRouter");
const stockRouter = require("./stockRouter");
const payrollRouter = require("./payrollRouter");
const shiftRouter = require("./shiftRouter");
const expendituresRouter = require("./expendituresRouter");
const serviceDetailRouter = require("./serviceDetailRouter");
const billRouter = require("./billRouter");
const employeeRouter = require("./employeeRouter");
const rootRouter = express.Router();
rootRouter.use("/api/room", roomRouter);
rootRouter.use("/api/stock", stockRouter);
rootRouter.use("/api/payroll", payrollRouter);
rootRouter.use("/api/shift", shiftRouter);
rootRouter.use("/api/expenditures", expendituresRouter);
rootRouter.use("/api/serviceDetail", serviceDetailRouter);
rootRouter.use("/api/bill", billRouter);
rootRouter.use("/api/employee", employeeRouter);
module.exports = rootRouter;
